### PR TITLE
package/libglu: compile with PIC

### PR DESCRIPTION
**Pull request by acgaudette**

### CODE REVIEW

**Comment by acgaudette** [comment]
@bitter

**Comment by bitter** [comment]
I'm fine with this fix but how does buildroot normally apply PIC when building static libraries? Could we instead make that option available to our configuration?

**Comment by acgaudette** [comment]
meant to post this comment quite awhile ago

it seems as though -fPIC is added on a case-by-case basis to static libs that function as dependencies to other packages building shared libs. there is no single way to achieve this given that packages vary and may use autotools, cmake, etc.

so to answer your question, buildroot does not normally apply PIC to static libraries in the general case, afaict. this is why BR2_PIC_PIE is available for shared libs only.
however, it is possible to specify global cflags through the toolchain wrapper, which is how BR2_PIC_PIE actually works. we could do this, but it would mean building all packages with PIC. I was surprised to find this wasn't an option by default.

**Comment by acgaudette** [comment]
in any event.
I added a new config option (UNITY3D_PACKAGE_LIBGLU_STATIC_PIC) to toggle this combined behavior:
- make libGLU.a, regardless of whether you are building all packages statically or not. this allows you to set BR2_SHARED_LIBS and save on space
- compile this binary with PIC

i.e.
> make that option available to our configuration

:+1:

**Review by bitter — APPROVED** [review]
LGTM

>it seems as though -fPIC is added on a case-by-case basis to static libs that function as dependencies to other packages building shared libs. there is no single way to achieve this given that packages vary and may use autotools, cmake, etc.

That is a bit weird as static libraries doesn't really need a PIC option. They are not linked. For static libraries only the compiler needs a PIC option. Unlike dynamic libraries, where both the compiler _and_ the linker needs to know this is position independent code.

**Pull request merged**
